store/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('products.urls')),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

store/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import User


class UserRegistrationForm(UserCreationForm):
    full_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = User
        fields = ('username', 'full_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})

store/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid col-9">
                <div class="navbar-collapse d-flex" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'category_list' %}">Перейти к категориям товаров</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'basket' %}">Перейти к корзине товаров</a>
                            </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_admin %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'admin:index' %}">Панель администратора</a>
                            </li>
                        {% endif %}
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-dark" href="{% url 'login' %}">Вход</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <form id="logout-form" method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-dark">Выйти</button>
                                </form>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container mt-5 col-md-9">
            {% if messages %}
                <div class="container mt-4">
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% elif message.tags == 'success' %}
                            <div class="alert alert-success" role="alert">
                                {{ message }}
                            </div>
                        {% else %}
                            <div class="alert alert-info" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}

            {% block content %}

            {% endblock %}
        </div>
    </main>
    <footer class="d-flex justify-content-center mt-auto py-3">
        Тляшок Эдуард Азаматович 221-329
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

store/templates/basket.html
{% extends "base.html" %}

{% block title %}Корзина{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Корзина товаров</h1>
    <div class="row">
        {% if products %}
            <div class="col">
                <div class="container d-flex justify-content-center">
                    <button onclick="generateReport()" class="btn btn-dark">Сформировать заказ</button>
                </div>
                <table class="table mt-2">
                    <thead>
                        <tr>
                            <th scope="col">Наименование товара</th>
                            <th scope="col">Цена</th>
                            <th scope="col">Количество</th>
                            <th scope="col">Итого</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in products %}
                            <tr>
                                <td>{{ item.product.product_name }}</td>
                                <td>{{ item.product.price }}</td>
                                <td id="count-{{ item.product.product_id }}">{{ item.count }}</td>
                                <td id="total-{{ item.product.product_id }}">{{ item.total_price }}</td>
                                <td class="d-flex">
                                    <button class="btn btn-primary me-2 w-30" onclick="updateBasket({{ item.product.product_id }}, 'add')">+</button>
                                    <button class="btn btn-danger w-30" onclick="updateBasket({{ item.product.product_id }}, 'remove')">-</button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p class="text-center">Ваша корзина пуста.</p>
        {% endif %}
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.23/jspdf.plugin.autotable.min.js"></script>

<script>
    function updateBasket(productId, action) {
        const url = action === 'add' ? '{% url "add_product" 0 %}'.replace('0', productId) : '{% url "delete_product" 0 %}'.replace('0', productId);
        fetch(url)
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    const countElement = document.getElementById('count-' + productId);
                    const totalElement = document.getElementById('total-' + productId);
                    const price = parseFloat(totalElement.textContent) / parseInt(countElement.textContent);
                    countElement.textContent = data.count;
                    totalElement.textContent = (price * data.count).toFixed(2);
                    if (data.count < 1) {
                        countElement.parentElement.remove();
                    }
                    location.reload();
                }
            })
            .catch(error => console.error('Error:', error));
    }
</script>

{% load static %}
<script src="{% static 'basket.js' %}"></script>

{% endblock %}

store/templates/categories.html
{% extends "base.html" %}

{% block title %}Выбор категории товара{% endblock %}

{% block content %}
<div class="container mt-5">
    <h3 class="text-center mb-4">Категории товаров</h3>
    <div class="row">
        {% for category in categories %}
            <div class="col-md-4 d-flex align-items-stretch">
                <div class="card mb-4" style="width: 18rem;">
                    <div class="card-img-top" style="height: 200px; overflow: hidden;">
                        <img src="{{ category.category_image.url }}" class="w-100 h-100" style="object-fit: cover;" alt="{{ category.category_name }}">
                    </div>
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{ category.category_name }}</h5>
                        <a href="{% url 'category_products' category.category_id %}" class="btn btn-primary mt-auto">Перейти к категории</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

store/templates/category_products.html
{% extends "base.html" %}

{% block title %}{{ category.category_name }}{% endblock %}

{% block content %}
<div class="container mt-5">
    <h3 class="text-center mb-4">{{ category.category_name }}</h3>
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header">
                    Фильтры
                </div>
                <div class="card-body">
                    <form id="filterForm" method="get">
                        <div id="filtersContainer">
                            <div class="form-group">
                                <label for="search_input">Поиск:</label>
                                <input type="text" class="form-control" id="search_input" name="search_input" placeholder="Поиск">
                            </div>
                            <div class="form-group">
                                <label for="price_min">Минимальная цена:</label>
                                <input type="number" class="form-control" id="price_min" name="price_min" placeholder="Минимальная цена">
                            </div>
                            <div class="form-group">
                                <label for="price_max">Максимальная цена:</label>
                                <input type="number" class="form-control" id="price_max" name="price_max" placeholder="Максимальная цена">
                            </div>
                            <div class="form-group">
                                <label for="sort_by_price">Сортировать по цене:</label>
                                <select class="form-select" id="sort_by_price" name="sort_by_price">
                                    <option value="asc">По возрастанию</option>
                                    <option value="desc">По убыванию</option>
                                </select>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Применить фильтры</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-9">
            <div class="row" id="productContainer" 
                 data-filters="{{ filters|escapejs }}" 
                 data-products="{{ products|escapejs }}">

            </div>
        </div>
    </div>
    <div id="authData" data-is-authenticated="{{ user.is_authenticated }}"></div>
</div>
{% load static %}
<script src="{% static 'app.js' %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const filters = JSON.parse('{{ filters|safe }}');
        const products = JSON.parse('{{ products|safe }}');
    
        initializeFilters(filters, products);
        displayProducts(products);
    });
</script>
{% endblock %}  

store/templates/index.html
{% extends "base.html" %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <p>Добро пожаловать, {% if user.full_name %} {{ user.full_name }} {% else %} anonymous {% endif %}!</p>
{% endblock %}

store/templates/login.html
{% extends "base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <h3 class="text-center">Вход</h3>
            <form method="post" class="mt-4">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_username" class="form-label">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label">Пароль</label>
                    {{ form.password }}
                </div>
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary">Войти</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

store/templates/register.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <h3 class="text-center">Регистрация</h3>
            <form method="post" class="mt-4">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_username" class="form-label">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="mb-3">
                    <label for="id_full_name" class="form-label">ФИО</label>
                    {{ form.full_name }}
                </div>
                <div class="mb-3">
                    <label for="id_password1" class="form-label">Пароль</label>
                    {{ form.password1 }}
                </div>
                <div class="mb-3">
                    <label for="id_password2" class="form-label">Подтверждение пароля</label>
                    {{ form.password2 }}
                </div>
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}